name: Integration tests
run-name: 🛠️ Running tests for ${{ github.actor }}'s PR.
on:
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize, edited, reopened ]
jobs:
  tests:
    name: Run Go tests
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mysql:8.0
        ports:
          - 3341:3341
        options:
          --name=mysql_container
        env:
          MYSQL_ROOT_HOST: "%"
          MYSQL_ROOT_PASSWORD: "secret"
          MYSQL_TCP_PORT: "3341"
          MYSQL_DATABASE: "theoverwatchtools"
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v2

      - name: Install go
        uses: actions/setup-go@v4
        with: { go-version: 1.21 }

      - name: Run go mod tidy
        run: |
          go mod tidy   

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.56.2
          skip-pkg-cache: true

      - name: Run go vet
        run: |
          go vet ./... 

      - name: Set MySQL sql_mode
        run: |
          echo "SET GLOBAL sql_mode = 'STRICT_TRANS_TABLES';" | docker exec -i mysql_container mysql -uroot -psecret theoverwatchtools

      - name: Run go test
        env:
          THEOVERWATCHTOOLS_PRODUCTION: "true"
          THEOVERWATCHTOOLS_APP_DIR: ${{ github.workspace }}
          API_BASE_URL: "http://localhost:3004"
          API_PORT: "3004"
          API_LISTEN_TIMEOUT_SECS: "10s"
          API_REQUEST_TIMEOUT_SECS: "10s"
          TIMEOUT_DB_EXEC: "10s"
          TIMEOUT_DB_QUERY: "10s"

          DB_HOST: "localhost"
          DB_USER: "root"
          DB_PASS: "secret"
          DB_PORT: "3341"
          DB_DATABASE: "theoverwatchtools"
        run: |
          go test ./... -v
